title: "trycksatt.se"
description: "Hydraulik och sprinklerteknik för branschproffs"
author: "Andreas Surell"
baseurl: ""
url: "https://trycksatt.se"

lang: sv
timezone: Europe/Stockholm

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

collections:
  posts:
    output: true
    permalink: /artiklar/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "artikel"
